import { canvasMachine } from "@/ui/machines/canvas.machine";
import type { Node } from "@xyflow/react";
import { describe, expect, it } from "vitest";
import { createActor } from "xstate";

/**
 * ADR-014 Phase 4, found while testing that the C4 dialect is refused.
 *
 * It is refused — but the refusal was catastrophic. `importDiagram` caught the
 * parse failure and substituted an empty result:
 *
 *   Effect.catchAll(parseEffect, () => Effect.succeed({ nodes: [], edges: [] }))
 *
 * and in "replace" mode that empty result *became the board*. So exporting the C4
 * dialect and importing it back — the most natural thing to try — silently
 * destroyed the diagram, with nothing but a console line to say why.
 *
 * A failed import must leave the board exactly as it was.
 */

const existingNode: Node = {
  id: "keep-me",
  type: "c4Node",
  position: { x: 100, y: 200 },
  data: { label: "Payments API", description: "", technology: "", c4Type: "container" },
};

const boardWith = (nodes: Node[]) => {
  const actor = createActor(canvasMachine).start();
  actor.send({ type: "IMPORT_DIAGRAM", content: mermaidFor(nodes), format: "mermaid", mode: "replace" });
  return actor;
};

/** A minimal valid flowchart export, so the board starts with something to lose. */
const mermaidFor = (nodes: Node[]) =>
  [
    "flowchart TB",
    ...nodes.flatMap((node) => [
      `    ${node.id.replace(/[^a-zA-Z0-9_]/g, "_")}[("${(node.data as { label: string }).label}")]`,
      `    %% @pos(${node.position.x},${node.position.y},220,120)`,
    ]),
  ].join("\n");

const C4_EXPORT = [
  "C4Container",
  "%% Generated by c4-board — Mermaid C4 (experimental).",
  "  Person(operator, \"Operator\")",
  "  Container(payments_api, \"Payments API\", \"Rust\")",
].join("\n");

describe("a failed import", () => {
  it("leaves the board alone when the file is the wrong dialect", () => {
    const actor = boardWith([existingNode]);
    const before = actor.getSnapshot().context.nodes;
    expect(before.length, "board did not load, so the test proves nothing").toBeGreaterThan(0);

    actor.send({ type: "IMPORT_DIAGRAM", content: C4_EXPORT, format: "mermaid", mode: "replace" });

    expect(actor.getSnapshot().context.nodes).toHaveLength(before.length);
  });

  it("leaves the board alone when the file is not a diagram at all", () => {
    const actor = boardWith([existingNode]);
    const before = actor.getSnapshot().context.nodes.length;

    actor.send({
      type: "IMPORT_DIAGRAM",
      content: "this is not a diagram",
      format: "mermaid",
      mode: "replace",
    });

    expect(actor.getSnapshot().context.nodes).toHaveLength(before);
  });

  it("reports why, rather than only writing to the console", () => {
    const actor = boardWith([existingNode]);

    actor.send({ type: "IMPORT_DIAGRAM", content: C4_EXPORT, format: "mermaid", mode: "replace" });

    const error = actor.getSnapshot().context.importError;
    expect(error, "no importError recorded").not.toBeNull();
    expect(error).toMatch(/C4/);
  });

  it("clears a previous error once an import succeeds", () => {
    const actor = boardWith([existingNode]);
    actor.send({ type: "IMPORT_DIAGRAM", content: C4_EXPORT, format: "mermaid", mode: "replace" });
    expect(actor.getSnapshot().context.importError).not.toBeNull();

    actor.send({
      type: "IMPORT_DIAGRAM",
      content: mermaidFor([existingNode]),
      format: "mermaid",
      mode: "replace",
    });

    expect(actor.getSnapshot().context.importError).toBeNull();
  });
});

describe("a successful import", () => {
  it("still replaces the board", () => {
    const actor = boardWith([existingNode]);

    expect(actor.getSnapshot().context.nodes.length).toBeGreaterThan(0);
  });
});
